### ISSUE TITLE
Add package.json keyword

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-template-framework7#2]
Apache Cordova has settled on a few keywords to discovery templates, so let's add them to this module:
https://github.com/phonegap/phonegap-template-react-hot-loader/blob/master/package.json#L40-L43

**Comment by devgeeks** [comment]
I think this has been done and shipped... @hollyschinsky ?

**Comment by mwbrooks** [comment]
Yep, `1.0.3` added keywords and it published to npm.
